#include "Core/N2CRoundTripVerification.h"
#include "AssetRegistryModule.h"
#include "Core/N2CCoverage.h"
#include "Core/N2CPatchImporter.h"
#include "Core/N2CStructuralSnapshot.h"
#include "Dom/JsonObject.h"
#include "Dom/JsonValue.h"
#include "Editor.h"
#include "Engine/Blueprint.h"
#include "HAL/FileManager.h"
#include "HAL/PlatformProcess.h"
#include "HAL/PlatformTime.h"
#include "Kismet2/KismetEditorUtilities.h"
#include "Misc/CommandLine.h"
#include "Misc/FileHelper.h"
#include "Misc/PackageName.h"
#include "Misc/Parse.h"
#include "Misc/Paths.h"
#include "Models/N2CLogging.h"
#include "PackageTools.h"
#include "Serialization/JsonReader.h"
#include "Serialization/JsonSerializer.h"
#include "Serialization/JsonWriter.h"
#include "Subsystems/AssetEditorSubsystem.h"
#include "UObject/Package.h"
#include "UObject/UObjectGlobals.h"

namespace N2CRoundTrip_Private
{
static void Append(FString& R,const FString& L){R+=L+LINE_TERMINATOR;UE_LOG(LogNodeToCode,Display,TEXT("%s"),*L);}
static bool Serialize(const TSharedPtr<FJsonObject>& O,FString& T){if(!O.IsValid())return false;auto W=TJsonWriterFactory<>::Create(&T);return FJsonSerializer::Serialize(O.ToSharedRef(),W);}
static bool WriteJsonAtomic(const FString& P,const TSharedPtr<FJsonObject>& O,FString& E){IFileManager::Get().MakeDirectory(*FPaths::GetPath(P),true);FString T;if(!Serialize(O,T)){E=TEXT("json_serialize_failed");return false;}const FString X=P+TEXT(".tmp");if(!FFileHelper::SaveStringToFile(T,*X,FFileHelper::EEncodingOptions::ForceUTF8WithoutBOM)){E=TEXT("temp_write_failed");return false;}if(!IFileManager::Get().Move(*P,*X,true,true)){E=TEXT("atomic_move_failed");return false;}if(!IFileManager::Get().FileExists(*P)){E=TEXT("final_artifact_missing");return false;}return true;}
static bool ReadJson(const FString& P,TSharedPtr<FJsonObject>& O,FString& E){FString T;if(!FFileHelper::LoadFileToString(T,*P)){E=TEXT("artifact_read_failed");return false;}auto R=TJsonReaderFactory<>::Create(T);if(!FJsonSerializer::Deserialize(R,O)||!O.IsValid()){E=TEXT("artifact_json_invalid");return false;}return true;}
static bool ParseJsonText(const FString& T,TSharedPtr<FJsonObject>& O,FString& E){auto R=TJsonReaderFactory<>::Create(T);if(!FJsonSerializer::Deserialize(R,O)||!O.IsValid()){E=TEXT("parse_failed");return false;}return true;}
static bool RequiredString(const TSharedPtr<FJsonObject>& O,const TCHAR* F,FString& V,FString& E){if(!O.IsValid()||!O->TryGetStringField(F,V)||V.IsEmpty()){E=FString::Printf(TEXT("missing_or_invalid_%s"),F);return false;}return true;}
static bool OptionalBool(const TSharedPtr<FJsonObject>& O,const TCHAR* F,bool D=false){bool V=D;if(O.IsValid())O->TryGetBoolField(F,V);return V;}
static const TCHAR* ChildStageName(EN2CRoundTripStage S){if(S==EN2CRoundTripStage::Parse)return TEXT("ParseRequest");if(S==EN2CRoundTripStage::Preflight)return TEXT("ValidateRequest");return FN2CRoundTripVerification::StageName(S);}
static TSharedPtr<FJsonObject> StageJsonNamed(const FN2CRoundTripStageResult& E,const TCHAR* Name){auto O=MakeShared<FJsonObject>();O->SetStringField(TEXT("stage"),Name);O->SetBoolField(TEXT("attempted"),E.bAttempted);O->SetBoolField(TEXT("passed"),E.bPassed);O->SetStringField(TEXT("error_code"),E.ErrorCode);O->SetStringField(TEXT("message"),E.Message);O->SetNumberField(TEXT("duration_seconds"),E.DurationSeconds);return O;}
static TSharedPtr<FJsonObject> StageJson(const FN2CRoundTripStageResult& E){return StageJsonNamed(E,FN2CRoundTripVerification::StageName(E.Stage));}
static TSharedPtr<FJsonObject> ChildStageJson(const FN2CRoundTripStageResult& E){return StageJsonNamed(E,ChildStageName(E.Stage));}
static void Record(FN2CRoundTripVerificationResult& O,FString& R,EN2CRoundTripStage S,bool P,const FString& C=FString(),const FString& M=FString(),double T=0){auto& E=O.StageResults.AddDefaulted_GetRef();E.Stage=S;E.bAttempted=true;E.bPassed=P;E.ErrorCode=C;E.Message=M;E.DurationSeconds=T>0?FPlatformTime::Seconds()-T:0;Append(R,FString::Printf(TEXT("N2C_ROUNDTRIP_STAGE|stage=%s|result=%s|code=%s|detail=%s"),FN2CRoundTripVerification::StageName(S),P?TEXT("PASS"):TEXT("FAIL"),*C,*M));}
static bool HasFault(const FN2CRoundTripVerificationRequest& R){return R.bForceCompileAfterApplyFailure||R.bForceSaveFailure||R.bForceMissingChildResult||R.bForceStructuralMismatch||R.bDelayChildForTimeout||R.bForceChildReloadFailure||R.bForceMalformedChildResult||R.bForceChildIdentityMismatch;}
static TSharedPtr<FJsonObject> ResultJson(const FN2CRoundTripVerificationResult& R){auto O=MakeShared<FJsonObject>();O->SetStringField(TEXT("schema"),TEXT("N2C_ROUNDTRIP_VERIFY_RESULT_V3"));O->SetStringField(TEXT("run_id"),R.RunId);O->SetStringField(TEXT("asset_path"),R.AssetPath);O->SetStringField(TEXT("patch_identity"),R.PatchIdentity);O->SetBoolField(TEXT("verification_passed"),R.bPassed);O->SetStringField(TEXT("failed_stage"),R.FailedStage);O->SetStringField(TEXT("error_code"),R.ErrorCode);O->SetNumberField(TEXT("parent_process_id"),R.ParentProcessId);O->SetNumberField(TEXT("child_process_id"),R.ChildProcessId);O->SetNumberField(TEXT("child_exit_code"),R.ChildExitCode);O->SetStringField(TEXT("manifest_path"),R.ManifestPath);O->SetStringField(TEXT("expected_contract_path"),R.ExpectedContractPath);O->SetStringField(TEXT("baseline_path"),R.BaselinePath);O->SetStringField(TEXT("diff_path"),R.DiffPath);O->SetStringField(TEXT("child_request_path"),R.ChildRequestPath);O->SetStringField(TEXT("child_result_path"),R.ChildResultPath);O->SetStringField(TEXT("fresh_log_path"),R.FreshLogPath);O->SetStringField(TEXT("backup_path"),R.BackupPath);O->SetBoolField(TEXT("weak_blueprint_alive_after_unload"),R.bWeakBlueprintAliveAfterUnload);O->SetBoolField(TEXT("package_shell_alive_after_unload"),R.bPackageShellAliveAfterUnload);O->SetBoolField(TEXT("cleanup_passed"),R.bCleanupPassed);TArray<TSharedPtr<FJsonValue>> A;for(const auto& E:R.StageResults)A.Add(MakeShared<FJsonValueObject>(StageJson(E)));O->SetArrayField(TEXT("stage_results"),A);return O;}
static bool CopyBackup(const FString& A,const FString& B,FString& S,FString& E){FString P=A;int32 D=INDEX_NONE;if(P.FindChar(TEXT('.'),D))P=P.Left(D);S=FPackageName::LongPackageNameToFilename(P,FPackageName::GetAssetPackageExtension());if(!IFileManager::Get().FileExists(*S)){E=TEXT("source_package_missing");return false;}IFileManager::Get().MakeDirectory(*FPaths::GetPath(B),true);if(IFileManager::Get().Copy(*B,*S,true,true)!=COPY_OK||!IFileManager::Get().FileExists(*B)){E=TEXT("backup_copy_failed");return false;}return true;}
static bool CleanupFixture(const FString& A,FString& E){if(!A.StartsWith(TEXT("/Game/N2C_Test/Generated/"))){E=TEXT("cleanup_path_not_generated");return false;}UBlueprint* B=LoadObject<UBlueprint>(nullptr,*A);UPackage* P=B?B->GetOutermost():nullptr;if(B){FModuleManager::LoadModuleChecked<FAssetRegistryModule>(TEXT("AssetRegistry")).Get().AssetDeleted(B);if(GEditor){GEditor->GetEditorSubsystem<UAssetEditorSubsystem>()->CloseAllEditorsForAsset(B);GEditor->ResetTransaction(NSLOCTEXT("NodeToCode","P0RoundTripCleanupDiscardUndo","P0 generated fixture cleanup"));}}B=nullptr;if(P){P->SetDirtyFlag(false);TArray<UPackage*> Ps;Ps.Add(P);FText X;if(!UPackageTools::UnloadPackages(Ps,X)){E=X.ToString();return false;}}P=nullptr;CollectGarbage(RF_NoFlags);FString N=A;int32 D=INDEX_NONE;if(N.FindChar(TEXT('.'),D))N=N.Left(D);const FString F=FPackageName::LongPackageNameToFilename(N,FPackageName::GetAssetPackageExtension());if(IFileManager::Get().FileExists(*F)&&!IFileManager::Get().Delete(*F,false,true,true)){E=TEXT("fixture_file_delete_failed");return false;}const bool bClean=!IFileManager::Get().FileExists(*F);UE_LOG(LogNodeToCode,Display,TEXT("N2C_FIXTURE_CLEANUP|asset=%s|result=%s"),*A,bClean?TEXT("PASS"):TEXT("FAIL"));return bClean;}
static TSharedPtr<FJsonObject> Manifest(const FN2CRoundTripVerificationRequest& Q,const FN2CRoundTripVerificationResult& R,const FString& X,const FString& S,const FString& E)
{
    auto O=MakeShared<FJsonObject>();O->SetStringField(TEXT("schema"),TEXT("N2C_ROUNDTRIP_RUN_MANIFEST_V1"));O->SetStringField(TEXT("run_id"),R.RunId);O->SetStringField(TEXT("asset"),R.AssetPath);O->SetStringField(TEXT("generated_fixture"),Q.GeneratedFixturePath);O->SetStringField(TEXT("template_asset"),Q.TemplateAssetPath);O->SetStringField(TEXT("patch_identity"),R.PatchIdentity);O->SetStringField(TEXT("backup_path"),R.BackupPath);O->SetNumberField(TEXT("parent_pid"),R.ParentProcessId);O->SetStringField(TEXT("child_executable"),X);O->SetNumberField(TEXT("timeout_seconds"),Q.FreshProcessTimeoutSeconds);O->SetStringField(TEXT("start_timestamp"),S);O->SetStringField(TEXT("end_timestamp"),E);O->SetBoolField(TEXT("cleanup_passed"),R.bCleanupPassed);
    auto A=MakeShared<FJsonObject>();A->SetStringField(TEXT("manifest"),R.ManifestPath);A->SetStringField(TEXT("expected_contract"),R.ExpectedContractPath);A->SetStringField(TEXT("persistence_baseline"),R.BaselinePath);A->SetStringField(TEXT("structural_diff"),R.DiffPath);A->SetStringField(TEXT("child_request"),R.ChildRequestPath);A->SetStringField(TEXT("child_result"),R.ChildResultPath);A->SetStringField(TEXT("fresh_log"),R.FreshLogPath);A->SetStringField(TEXT("parent_result"),FPaths::Combine(R.RunDirectory,TEXT("roundtrip_result.json")));O->SetObjectField(TEXT("artifact_paths"),A);
    auto F=MakeShared<FJsonObject>();F->SetBoolField(TEXT("compile_after_apply_failure"),Q.bForceCompileAfterApplyFailure);F->SetBoolField(TEXT("save_failure"),Q.bForceSaveFailure);F->SetBoolField(TEXT("missing_child_result"),Q.bForceMissingChildResult);F->SetBoolField(TEXT("structural_mismatch"),Q.bForceStructuralMismatch);F->SetBoolField(TEXT("child_timeout"),Q.bDelayChildForTimeout);F->SetBoolField(TEXT("child_reload_failure"),Q.bForceChildReloadFailure);F->SetBoolField(TEXT("malformed_child_result"),Q.bForceMalformedChildResult);F->SetBoolField(TEXT("child_identity_mismatch"),Q.bForceChildIdentityMismatch);O->SetObjectField(TEXT("fault_flags"),F);return O;
}
static TSharedPtr<FJsonObject> ChildRequest(const FN2CRoundTripVerificationRequest& Q,const FN2CRoundTripVerificationResult& R,const FString& B,const FString& C){auto O=MakeShared<FJsonObject>();O->SetStringField(TEXT("schema"),TEXT("N2C_FRESH_VERIFY_REQUEST_V3"));O->SetStringField(TEXT("run_id"),R.RunId);O->SetStringField(TEXT("asset_path"),R.AssetPath);O->SetStringField(TEXT("baseline_path"),R.BaselinePath);O->SetStringField(TEXT("baseline_hash"),B);O->SetStringField(TEXT("expected_contract_path"),R.ExpectedContractPath);O->SetStringField(TEXT("expected_contract_hash"),C);O->SetStringField(TEXT("diff_path"),R.DiffPath);O->SetStringField(TEXT("result_path"),R.ChildResultPath);O->SetBoolField(TEXT("force_missing_result"),Q.bForceMissingChildResult);O->SetBoolField(TEXT("force_structural_mismatch"),Q.bForceStructuralMismatch);O->SetBoolField(TEXT("delay_for_timeout"),Q.bDelayChildForTimeout);O->SetBoolField(TEXT("force_child_reload_failure"),Q.bForceChildReloadFailure);O->SetBoolField(TEXT("force_malformed_result"),Q.bForceMalformedChildResult);O->SetBoolField(TEXT("force_identity_mismatch"),Q.bForceChildIdentityMismatch);return O;}
static bool ChildStages(const TSharedPtr<FJsonObject>& R,bool bVerdict,const FString& FailedStage,const FString& ErrorCode,FString& E)
{
    const TArray<TSharedPtr<FJsonValue>>* Values=nullptr;
    if(!R.IsValid()||!R->TryGetArrayField(TEXT("stage_results"),Values)||!Values||Values->Num()==0){E=TEXT("child_stage_results_missing");return false;}
    const TSet<FString> Allowed={TEXT("ParseRequest"),TEXT("ValidateRequest"),TEXT("ReloadFromDisk"),TEXT("CompileAfterReload"),TEXT("BuildReloadedSnapshot"),TEXT("ExpectedContractCompare"),TEXT("PersistenceCompare"),TEXT("WriteDiff"),TEXT("WriteResult"),TEXT("Finalize")};
    TMap<FString,bool> Passed;
    int32 FailureCount=0;
    for(const TSharedPtr<FJsonValue>& Value:*Values)
    {
        if(!Value.IsValid()||Value->Type!=EJson::Object){E=TEXT("child_stage_entry_invalid");return false;}
        const TSharedPtr<FJsonObject> Obj=Value->AsObject();FString Name,StageCode,Message;bool bAttempted=false,bPassed=false;double Duration=0;
        if(!Obj.IsValid()||!Obj->TryGetStringField(TEXT("stage"),Name)||!Allowed.Contains(Name)||Passed.Contains(Name)||!Obj->TryGetBoolField(TEXT("attempted"),bAttempted)||!Obj->TryGetBoolField(TEXT("passed"),bPassed)||!Obj->TryGetStringField(TEXT("error_code"),StageCode)||!Obj->TryGetStringField(TEXT("message"),Message)||!Obj->TryGetNumberField(TEXT("duration_seconds"),Duration)||!bAttempted||Duration<0){E=TEXT("child_stage_entry_invalid");return false;}
        if(!bPassed){++FailureCount;if(Name!=FailedStage||StageCode.IsEmpty()){E=TEXT("child_stage_failure_mismatch");return false;}}
        Passed.Add(Name,bPassed);
    }
    const TArray<FString> Always={TEXT("ParseRequest"),TEXT("ValidateRequest"),TEXT("WriteDiff"),TEXT("WriteResult"),TEXT("Finalize")};
    for(const FString& Name:Always){if(!Passed.Contains(Name)||!Passed[Name]){E=TEXT("child_required_stage_missing");return false;}}
    if(bVerdict)
    {
        const TArray<FString> Success={TEXT("ReloadFromDisk"),TEXT("CompileAfterReload"),TEXT("BuildReloadedSnapshot"),TEXT("ExpectedContractCompare"),TEXT("PersistenceCompare")};
        if(!FailedStage.IsEmpty()||!ErrorCode.IsEmpty()||FailureCount!=0){E=TEXT("child_verdict_contradiction");return false;}
        for(const FString& Name:Success){if(!Passed.Contains(Name)||!Passed[Name]){E=TEXT("child_required_stage_missing");return false;}}
    }
    else if(FailedStage.IsEmpty()||ErrorCode.IsEmpty()||FailureCount!=1||!Passed.Contains(FailedStage)||Passed[FailedStage]){E=TEXT("child_verdict_contradiction");return false;}
    return true;
}
static FString PreflightErrorCode(const FString& Report){const TCHAR* Codes[]={TEXT("member_default_import_text_invalid"),TEXT("macro_owner_missing"),TEXT("macro_graph_missing"),TEXT("macro_signature_mismatch"),TEXT("macro_reference_unsupported"),TEXT("macro_dependency_cycle"),TEXT("struct_identity_missing"),TEXT("struct_member_mismatch"),TEXT("enum_identity_missing"),TEXT("enum_case_mismatch"),TEXT("datatable_identity_missing"),TEXT("datatable_signature_mismatch"),TEXT("create_widget_class_identity_missing"),TEXT("input_action_identity_missing"),TEXT("input_key_identity_missing"),TEXT("make_array_type_missing"),TEXT("delegate_identity_mismatch"),TEXT("unsupported_parameter_default"),TEXT("unsupported_local_default"),TEXT("unsupported_parameter_flags"),TEXT("unsupported_reference_default"),TEXT("enum_member_type_unresolved")};for(const TCHAR* Code:Codes)if(Report.Contains(FString(TEXT("code="))+Code))return Code;return FString();}
}const TCHAR* FN2CRoundTripVerification::StageName(EN2CRoundTripStage S){switch(S){case EN2CRoundTripStage::Parse:return TEXT("Parse");case EN2CRoundTripStage::Preflight:return TEXT("Preflight");case EN2CRoundTripStage::Backup:return TEXT("Backup");case EN2CRoundTripStage::Apply:return TEXT("Apply");case EN2CRoundTripStage::CompileAfterApply:return TEXT("CompileAfterApply");case EN2CRoundTripStage::BuildExpectedContract:return TEXT("BuildExpectedContract");case EN2CRoundTripStage::BuildPersistenceBaseline:return TEXT("BuildPersistenceBaseline");case EN2CRoundTripStage::Save:return TEXT("Save");case EN2CRoundTripStage::CloseEditors:return TEXT("CloseEditors");case EN2CRoundTripStage::Unload:return TEXT("Unload");case EN2CRoundTripStage::LaunchFreshProcess:return TEXT("LaunchFreshProcess");case EN2CRoundTripStage::ParseChildResult:return TEXT("ParseChildResult");case EN2CRoundTripStage::ReloadFromDisk:return TEXT("ReloadFromDisk");case EN2CRoundTripStage::CompileAfterReload:return TEXT("CompileAfterReload");case EN2CRoundTripStage::BuildReloadedSnapshot:return TEXT("BuildReloadedSnapshot");case EN2CRoundTripStage::ExpectedContractCompare:return TEXT("ExpectedContractCompare");case EN2CRoundTripStage::PersistenceCompare:return TEXT("PersistenceCompare");case EN2CRoundTripStage::WriteDiff:return TEXT("WriteDiff");case EN2CRoundTripStage::WriteResult:return TEXT("WriteResult");case EN2CRoundTripStage::RestoreAfterFailure:return TEXT("RestoreAfterFailure");case EN2CRoundTripStage::CleanupFixture:return TEXT("CleanupFixture");default:return TEXT("Finalize");}}
bool FN2CRoundTripVerification::HasPassedStage(const FN2CRoundTripVerificationResult& R,EN2CRoundTripStage S){for(const auto& E:R.StageResults)if(E.Stage==S&&E.bAttempted&&E.bPassed)return true;return false;}

bool FN2CRoundTripVerification::RunParent(const FN2CRoundTripVerificationRequest& I,FN2CRoundTripVerificationResult& O)
{
using namespace N2CRoundTrip_Private;O=FN2CRoundTripVerificationResult();auto Q=I;if(Q.RunId.IsEmpty())Q.RunId=FString::Printf(TEXT("P0RoundTrip_%lld"),FDateTime::UtcNow().GetTicks());O.RunId=Q.RunId;O.AssetPath=Q.AssetPath;O.PatchIdentity=Q.PatchIdentity.IsEmpty()?TEXT("inline_patch"):Q.PatchIdentity;O.ParentProcessId=FPlatformProcess::GetCurrentProcessId();O.RunDirectory=Q.RunDirectory.IsEmpty()?FPaths::Combine(FPaths::ProjectSavedDir(),TEXT("NodeToCode/VerificationRuns"),Q.RunId):Q.RunDirectory;IFileManager::Get().MakeDirectory(*O.RunDirectory,true);O.ManifestPath=FPaths::Combine(O.RunDirectory,TEXT("run_manifest.json"));O.ExpectedContractPath=FPaths::Combine(O.RunDirectory,TEXT("expected_contract.json"));O.BaselinePath=FPaths::Combine(O.RunDirectory,TEXT("persistence_baseline.json"));O.DiffPath=FPaths::Combine(O.RunDirectory,TEXT("structural_diff.json"));O.ChildRequestPath=FPaths::Combine(O.RunDirectory,TEXT("fresh_request.json"));O.ChildResultPath=FPaths::Combine(O.RunDirectory,TEXT("fresh_result.json"));O.FreshLogPath=FPaths::Combine(O.RunDirectory,TEXT("fresh_process.log"));O.BackupPath=FPaths::Combine(O.RunDirectory,TEXT("fixture_before_apply.uasset"));const FString ChildExe=FPaths::Combine(FPaths::EngineDir(),TEXT("Binaries/Win64/UE4Editor-Cmd.exe"));const FString Start=FDateTime::UtcNow().ToIso8601();FString R,E,Source;bool Mutated=false;Append(R,FString::Printf(TEXT("N2C_ROUNDTRIP_BEGIN|schema=V3|run_id=%s|asset=%s"),*Q.RunId,*Q.AssetPath));
auto Finish=[&](){FString X;WriteJsonAtomic(O.ManifestPath,Manifest(Q,O,ChildExe,Start,FDateTime::UtcNow().ToIso8601()),X);if(!WriteJsonAtomic(FPaths::Combine(O.RunDirectory,TEXT("roundtrip_result.json")),ResultJson(O),X)&&O.ErrorCode.IsEmpty()){O.bPassed=false;O.FailedStage=StageName(EN2CRoundTripStage::WriteResult);O.ErrorCode=TEXT("parent_result_write_failed");}O.Report=R;};
auto Recover=[&](){double T=FPlatformTime::Seconds();FString X;bool P=false;if(Q.bCleanupGeneratedFixture&&!Q.GeneratedFixturePath.IsEmpty())P=CleanupFixture(Q.GeneratedFixturePath,X);else if(Mutated&&!O.BackupPath.IsEmpty()&&!Source.IsEmpty())P=IFileManager::Get().Copy(*Source,*O.BackupPath,true,true)==COPY_OK;else return;Record(O,R,Mutated?EN2CRoundTripStage::RestoreAfterFailure:EN2CRoundTripStage::CleanupFixture,P,P?FString():(Mutated?TEXT("restore_failed"):TEXT("cleanup_failed")),X,T);O.bCleanupPassed=P;};
auto Fail=[&](EN2CRoundTripStage S,const FString& C,const FString& M){Record(O,R,S,false,C,M);O.bPassed=false;O.FailedStage=StageName(S);O.ErrorCode=C;Recover();Finish();return false;};
if(HasFault(Q)&&!Q.bAutomationOnly)return Fail(EN2CRoundTripStage::Parse,TEXT("test_fault_injection_not_allowed"),TEXT("fault flags require bAutomationOnly"));
TSharedPtr<FJsonObject> Patch;double T=FPlatformTime::Seconds();if(!ParseJsonText(Q.PatchJson,Patch,E))return Fail(EN2CRoundTripStage::Parse,TEXT("parse_failed"),E);FString S;if(!Patch->TryGetStringField(TEXT("schema"),S)||S!=TEXT("N2C_PATCH_V1"))return Fail(EN2CRoundTripStage::Parse,TEXT("parse_failed"),TEXT("N2C_PATCH_V1 required"));Record(O,R,EN2CRoundTripStage::Parse,true,FString(),FString(),T);
UBlueprint* B=LoadObject<UBlueprint>(nullptr,*Q.AssetPath);if(!B)return Fail(EN2CRoundTripStage::Preflight,TEXT("preflight_blocked"),TEXT("fixture asset could not load"));FN2CPreflightResult P;FString PR;T=FPlatformTime::Seconds();if(!FN2CPatchImporter::PreflightPatch(B,Q.PatchJson,Q.bDeveloperOverride,P,PR)){const FString PC=PreflightErrorCode(PR);return Fail(EN2CRoundTripStage::Preflight,PC.IsEmpty()?TEXT("preflight_blocked"):PC,PR);}Record(O,R,EN2CRoundTripStage::Preflight,true,FString(),PR,T);
T=FPlatformTime::Seconds();if(!CopyBackup(Q.AssetPath,O.BackupPath,Source,E))return Fail(EN2CRoundTripStage::Backup,TEXT("backup_failed"),E);Record(O,R,EN2CRoundTripStage::Backup,true,FString(),O.BackupPath,T);Mutated=true;FString AR;T=FPlatformTime::Seconds();if(!FN2CPatchImporter::ApplyPatchToBlueprint(B,Q.PatchJson,AR,Q.bDeveloperOverride,false))return Fail(EN2CRoundTripStage::Apply,TEXT("apply_failed"),AR);Record(O,R,EN2CRoundTripStage::Apply,true,FString(),AR,T);
T=FPlatformTime::Seconds();if(Q.bForceCompileAfterApplyFailure){Append(R,TEXT("N2C_TEST_FAULT_INJECTION|type=compile_after_apply"));return Fail(EN2CRoundTripStage::CompileAfterApply,TEXT("compile_after_apply_failed"),TEXT("test_fault_injection"));}FKismetEditorUtilities::CompileBlueprint(B);if(B->Status==BS_Error)return Fail(EN2CRoundTripStage::CompileAfterApply,TEXT("compile_after_apply_failed"),TEXT("Blueprint status BS_Error"));Record(O,R,EN2CRoundTripStage::CompileAfterApply,true,FString(),FString(),T);
TSharedPtr<FJsonObject> C;T=FPlatformTime::Seconds();if(Q.ExpectedContractJson.IsEmpty()){C=MakeShared<FJsonObject>();C->SetStringField(TEXT("schema"),TEXT("N2C_EXPECTED_CONTRACT_V1"));TArray<TSharedPtr<FJsonValue>> Empty;C->SetArrayField(TEXT("required_nodes"),Empty);}else if(!ParseJsonText(Q.ExpectedContractJson,C,E))return Fail(EN2CRoundTripStage::BuildExpectedContract,TEXT("expected_contract_build_failed"),E);FString CH;if(!FN2CStructuralSnapshot::HashJson(C,CH,E)||!WriteJsonAtomic(O.ExpectedContractPath,C,E))return Fail(EN2CRoundTripStage::BuildExpectedContract,TEXT("expected_contract_build_failed"),E);Record(O,R,EN2CRoundTripStage::BuildExpectedContract,true,FString(),CH,T);
TSharedPtr<FJsonObject> Base;FString BH;T=FPlatformTime::Seconds();if(!FN2CStructuralSnapshot::Build(B,Base,BH,E)||!WriteJsonAtomic(O.BaselinePath,Base,E))return Fail(EN2CRoundTripStage::BuildPersistenceBaseline,TEXT("baseline_write_failed"),E);TSharedPtr<FJsonObject> D;if(!FN2CStructuralSnapshot::ValidateExpectedContract(C,Base,D,E)){WriteJsonAtomic(O.DiffPath,D,E);return Fail(EN2CRoundTripStage::BuildPersistenceBaseline,TEXT("expected_contract_mismatch"),E);}Record(O,R,EN2CRoundTripStage::BuildPersistenceBaseline,true,FString(),BH,T);
UPackage* Pack=B->GetOutermost();const FString PN=Pack->GetName();const FString F=FPackageName::LongPackageNameToFilename(PN,FPackageName::GetAssetPackageExtension());T=FPlatformTime::Seconds();if(Q.bForceSaveFailure){Append(R,TEXT("N2C_TEST_FAULT_INJECTION|type=save"));return Fail(EN2CRoundTripStage::Save,TEXT("save_failed"),TEXT("test_fault_injection"));}Pack->MarkPackageDirty();if(!UPackage::SavePackage(Pack,B,RF_Public|RF_Standalone,*F,GError,nullptr,false,true,SAVE_NoError)||Pack->IsDirty()||!IFileManager::Get().FileExists(*F))return Fail(EN2CRoundTripStage::Save,TEXT("save_failed"),F);Record(O,R,EN2CRoundTripStage::Save,true,FString(),F,T);
T=FPlatformTime::Seconds();if(GEditor){GEditor->GetEditorSubsystem<UAssetEditorSubsystem>()->CloseAllEditorsForAsset(B);if(Q.bAutomationOnly)GEditor->ResetTransaction(NSLOCTEXT("NodeToCode","P0RoundTripDiscardUndo","P0 generated fixture unload"));}Record(O,R,EN2CRoundTripStage::CloseEditors,true,FString(),FString(),T);TWeakObjectPtr<UBlueprint> W(B);B=nullptr;Pack=nullptr;UPackage* LP=FindPackage(nullptr,*PN);TArray<UPackage*> Ps;if(LP)Ps.Add(LP);FText UE;T=FPlatformTime::Seconds();if(Ps.Num()==0||!UPackageTools::UnloadPackages(Ps,UE))return Fail(EN2CRoundTripStage::Unload,TEXT("unload_failed"),UE.ToString());LP=nullptr;Ps.Reset();CollectGarbage(RF_NoFlags);O.bWeakBlueprintAliveAfterUnload=W.IsValid();O.bPackageShellAliveAfterUnload=FindPackage(nullptr,*PN)!=nullptr;if(O.bWeakBlueprintAliveAfterUnload)return Fail(EN2CRoundTripStage::Unload,TEXT("blueprint_still_loaded"),PN);Record(O,R,EN2CRoundTripStage::Unload,true,FString(),FString::Printf(TEXT("package_shell_alive=%d"),O.bPackageShellAliveAfterUnload?1:0),T);if(!WriteJsonAtomic(O.ChildRequestPath,ChildRequest(Q,O,BH,CH),E))return Fail(EN2CRoundTripStage::LaunchFreshProcess,TEXT("fresh_process_launch_failed"),E);const FString Args=FString::Printf(TEXT("\"%s\" -unattended -nop4 -NoSplash -NullRHI -ExecCmds=\"Automation RunTests NodeToCode.Verification.P0RoundTrip.Fresh; Quit\" -TestExit=\"Automation Test Queue Empty\" -N2CRoundTripRequest=\"%s\" -AbsLog=\"%s\""),*FPaths::GetProjectFilePath(),*O.ChildRequestPath,*O.FreshLogPath);uint32 PID=0;T=FPlatformTime::Seconds();FProcHandle Proc=FPlatformProcess::CreateProc(*ChildExe,*Args,true,false,true,&PID,0,*FPaths::ProjectDir(),nullptr,nullptr);O.ChildProcessId=PID;if(!Proc.IsValid())return Fail(EN2CRoundTripStage::LaunchFreshProcess,TEXT("fresh_process_launch_failed"),ChildExe);Record(O,R,EN2CRoundTripStage::LaunchFreshProcess,true,FString(),FString::Printf(TEXT("pid=%u"),PID),T);const double Wait=FPlatformTime::Seconds();while(FPlatformProcess::IsProcRunning(Proc)&&FPlatformTime::Seconds()-Wait<Q.FreshProcessTimeoutSeconds)FPlatformProcess::Sleep(.1f);if(FPlatformProcess::IsProcRunning(Proc)){FPlatformProcess::TerminateProc(Proc,true);FPlatformProcess::CloseProc(Proc);return Fail(EN2CRoundTripStage::ParseChildResult,TEXT("fresh_process_timeout"),FString::FromInt(Q.FreshProcessTimeoutSeconds));}int32 Exit=-1;FPlatformProcess::GetProcReturnCode(Proc,&Exit);FPlatformProcess::CloseProc(Proc);O.ChildExitCode=Exit;if(Exit!=0)return Fail(EN2CRoundTripStage::ParseChildResult,TEXT("fresh_process_nonzero_exit"),FString::FromInt(Exit));if(!IFileManager::Get().FileExists(*O.ChildResultPath))return Fail(EN2CRoundTripStage::ParseChildResult,TEXT("verification_artifact_missing"),O.ChildResultPath);
TSharedPtr<FJsonObject> CR;T=FPlatformTime::Seconds();if(!ReadJson(O.ChildResultPath,CR,E))return Fail(EN2CRoundTripStage::ParseChildResult,TEXT("child_result_invalid"),E);FString CS,RI,AP,BHX,CHX,FS,EC,CD;bool VP=false;double CP=0;
if(!CR->TryGetStringField(TEXT("schema"),CS)||CS!=TEXT("N2C_FRESH_VERIFY_RESULT_V3")||!CR->TryGetStringField(TEXT("run_id"),RI)||!CR->TryGetStringField(TEXT("asset_path"),AP)||!CR->TryGetStringField(TEXT("baseline_hash"),BHX)||!CR->TryGetStringField(TEXT("expected_contract_hash"),CHX)||!CR->TryGetBoolField(TEXT("verification_passed"),VP)||!CR->TryGetNumberField(TEXT("child_pid"),CP)||!CR->TryGetStringField(TEXT("failed_stage"),FS)||!CR->TryGetStringField(TEXT("error_code"),EC)||!ChildStages(CR,VP,FS,EC,E))return Fail(EN2CRoundTripStage::ParseChildResult,TEXT("child_result_invalid"),E);
if(RI!=Q.RunId||AP!=Q.AssetPath||BHX!=BH||CHX!=CH||static_cast<uint32>(CP)!=PID)return Fail(EN2CRoundTripStage::ParseChildResult,TEXT("child_identity_mismatch"),TEXT("run/asset/hash/pid mismatch"));Record(O,R,EN2CRoundTripStage::ParseChildResult,true,FString(),FString(),T);CR->TryGetStringField(TEXT("detail"),CD);
if(!VP){EN2CRoundTripStage X=FS==TEXT("ReloadFromDisk")?EN2CRoundTripStage::ReloadFromDisk:FS==TEXT("CompileAfterReload")?EN2CRoundTripStage::CompileAfterReload:FS==TEXT("BuildReloadedSnapshot")?EN2CRoundTripStage::BuildReloadedSnapshot:FS==TEXT("ExpectedContractCompare")?EN2CRoundTripStage::ExpectedContractCompare:FS==TEXT("WriteDiff")?EN2CRoundTripStage::WriteDiff:EN2CRoundTripStage::PersistenceCompare;return Fail(X,EC,CD.IsEmpty()?FS:CD);}
Record(O,R,EN2CRoundTripStage::ReloadFromDisk,true);Record(O,R,EN2CRoundTripStage::CompileAfterReload,true);Record(O,R,EN2CRoundTripStage::BuildReloadedSnapshot,true);Record(O,R,EN2CRoundTripStage::ExpectedContractCompare,true);Record(O,R,EN2CRoundTripStage::PersistenceCompare,true);Record(O,R,EN2CRoundTripStage::WriteDiff,true);if(Q.bCleanupGeneratedFixture&&!Q.GeneratedFixturePath.IsEmpty()){T=FPlatformTime::Seconds();O.bCleanupPassed=CleanupFixture(Q.GeneratedFixturePath,E);Record(O,R,EN2CRoundTripStage::CleanupFixture,O.bCleanupPassed,O.bCleanupPassed?FString():TEXT("cleanup_failed"),E,T);if(!O.bCleanupPassed)return Fail(EN2CRoundTripStage::CleanupFixture,TEXT("cleanup_failed"),E);}else O.bCleanupPassed=true;O.bPassed=true;O.FailedStage.Empty();O.ErrorCode.Empty();Record(O,R,EN2CRoundTripStage::Finalize,true);Append(R,TEXT("N2C_ROUNDTRIP_RESULT|result=PASS"));Finish();return true;
}bool FN2CRoundTripVerification::RunFreshChildFromCommandLine(FString& R)
{
using namespace N2CRoundTrip_Private;R.Empty();FString RP;if(!FParse::Value(FCommandLine::Get(),TEXT("N2CRoundTripRequest="),RP))return false;RP.TrimQuotesInline();TArray<FN2CRoundTripStageResult> Stages;auto Rec=[&](EN2CRoundTripStage S,bool P,const FString& C=FString(),const FString& M=FString()){auto& E=Stages.AddDefaulted_GetRef();E.Stage=S;E.bAttempted=true;E.bPassed=P;E.ErrorCode=C;E.Message=M;Append(R,FString::Printf(TEXT("N2C_FRESH_STAGE|stage=%s|result=%s|code=%s"),StageName(S),P?TEXT("PASS"):TEXT("FAIL"),*C));};TSharedPtr<FJsonObject> Q;FString E;if(!ReadJson(RP,Q,E)){Append(R,TEXT("N2C_FRESH_VERIFY_RESULT_V3|result=FAIL|code=parse_failed"));return true;}FString S,RI,AP,BP,BH,CP,CH,DP,OP;if(!RequiredString(Q,TEXT("schema"),S,E)||S!=TEXT("N2C_FRESH_VERIFY_REQUEST_V3")){Append(R,TEXT("N2C_FRESH_VERIFY_RESULT_V3|result=FAIL|code=parse_failed"));return true;}Rec(EN2CRoundTripStage::Parse,true);if(!RequiredString(Q,TEXT("run_id"),RI,E)||!RequiredString(Q,TEXT("asset_path"),AP,E)||!RequiredString(Q,TEXT("baseline_path"),BP,E)||!RequiredString(Q,TEXT("baseline_hash"),BH,E)||!RequiredString(Q,TEXT("expected_contract_path"),CP,E)||!RequiredString(Q,TEXT("expected_contract_hash"),CH,E)||!RequiredString(Q,TEXT("diff_path"),DP,E)||!RequiredString(Q,TEXT("result_path"),OP,E)){Append(R,TEXT("N2C_FRESH_VERIFY_RESULT_V3|result=FAIL|code=parse_failed"));return true;}Rec(EN2CRoundTripStage::Preflight,true);if(OptionalBool(Q,TEXT("delay_for_timeout")))FPlatformProcess::Sleep(5.f);if(OptionalBool(Q,TEXT("force_missing_result"))){Append(R,TEXT("N2C_TEST_FAULT_INJECTION|type=missing_child_result"));return true;}
bool Pass=true;FString Failed,Code,Detail;TSharedPtr<FJsonObject> Diff=MakeShared<FJsonObject>();Diff->SetStringField(TEXT("schema"),TEXT("N2C_STRUCTURAL_DIFF_V1"));UBlueprint* B=OptionalBool(Q,TEXT("force_child_reload_failure"))?nullptr:LoadObject<UBlueprint>(nullptr,*AP);if(!B){Pass=false;Failed=StageName(EN2CRoundTripStage::ReloadFromDisk);Code=TEXT("reload_failed");Detail=AP;Rec(EN2CRoundTripStage::ReloadFromDisk,false,Code,Detail);}else{Rec(EN2CRoundTripStage::ReloadFromDisk,true);Append(R,TEXT("N2C_FRESH_RELOAD|result=PASS"));}if(Pass){FKismetEditorUtilities::CompileBlueprint(B);if(B->Status==BS_Error){Pass=false;Failed=StageName(EN2CRoundTripStage::CompileAfterReload);Code=TEXT("compile_after_reload_failed");Rec(EN2CRoundTripStage::CompileAfterReload,false,Code);}else{Rec(EN2CRoundTripStage::CompileAfterReload,true);Append(R,TEXT("N2C_FRESH_RECOMPILE|result=PASS"));}}
TSharedPtr<FJsonObject> Actual,Base,Contract;FString AH;if(Pass&&!FN2CStructuralSnapshot::Build(B,Actual,AH,E)){Pass=false;Failed=StageName(EN2CRoundTripStage::BuildReloadedSnapshot);Code=TEXT("structural_compare_failed");Detail=E;Rec(EN2CRoundTripStage::BuildReloadedSnapshot,false,Code,Detail);}else if(Pass){FString SnapshotWriteError;WriteJsonAtomic(FPaths::Combine(FPaths::GetPath(OP),TEXT("reloaded_snapshot.json")),Actual,SnapshotWriteError);Rec(EN2CRoundTripStage::BuildReloadedSnapshot,true);}if(Pass&&(!ReadJson(BP,Base,E)||!ReadJson(CP,Contract,E))){Pass=false;Failed=StageName(EN2CRoundTripStage::BuildReloadedSnapshot);Code=TEXT("child_result_invalid");Detail=E;}if(Pass&&!FN2CStructuralSnapshot::ValidateExpectedContract(Contract,Actual,Diff,E)){Pass=false;Failed=StageName(EN2CRoundTripStage::ExpectedContractCompare);Code=TEXT("expected_contract_mismatch");Detail=E;Rec(EN2CRoundTripStage::ExpectedContractCompare,false,Code,Detail);}else if(Pass){Rec(EN2CRoundTripStage::ExpectedContractCompare,true);Append(R,TEXT("N2C_EXPECTED_CONTRACT_COMPARE|result=PASS"));}if(Pass&&OptionalBool(Q,TEXT("force_structural_mismatch"))){Actual->SetStringField(TEXT("test_fault_injection"),TEXT("structural_mismatch"));Append(R,TEXT("N2C_TEST_FAULT_INJECTION|type=structural_mismatch"));}if(Pass&&!FN2CStructuralSnapshot::Compare(Base,Actual,Diff,E)){Pass=false;Failed=StageName(EN2CRoundTripStage::PersistenceCompare);Code=TEXT("persistence_compare_failed");Detail=E;Rec(EN2CRoundTripStage::PersistenceCompare,false,Code,Detail);}else if(Pass){Rec(EN2CRoundTripStage::PersistenceCompare,true);Append(R,TEXT("N2C_PERSISTENCE_COMPARE|result=PASS"));}FString Ignore;const bool bDiffWritten=WriteJsonAtomic(DP,Diff,Ignore);if(!bDiffWritten&&Pass){Pass=false;Failed=StageName(EN2CRoundTripStage::WriteDiff);Code=TEXT("structural_compare_failed");Detail=Ignore;}Rec(EN2CRoundTripStage::WriteDiff,bDiffWritten,bDiffWritten?FString():TEXT("structural_compare_failed"),Ignore);
Rec(EN2CRoundTripStage::WriteResult,true);Rec(EN2CRoundTripStage::Finalize,true);auto O=MakeShared<FJsonObject>();O->SetStringField(TEXT("schema"),TEXT("N2C_FRESH_VERIFY_RESULT_V3"));O->SetStringField(TEXT("run_id"),OptionalBool(Q,TEXT("force_identity_mismatch"))?RI+TEXT("_wrong"):RI);O->SetStringField(TEXT("asset_path"),AP);O->SetNumberField(TEXT("child_pid"),FPlatformProcess::GetCurrentProcessId());O->SetStringField(TEXT("baseline_hash"),BH);O->SetStringField(TEXT("expected_contract_hash"),CH);O->SetBoolField(TEXT("verification_passed"),Pass);O->SetStringField(TEXT("failed_stage"),Failed);O->SetStringField(TEXT("error_code"),Code);O->SetStringField(TEXT("detail"),Detail);TArray<TSharedPtr<FJsonValue>> SV;for(const auto& X:Stages)SV.Add(MakeShared<FJsonValueObject>(ChildStageJson(X)));O->SetArrayField(TEXT("stage_results"),SV);if(OptionalBool(Q,TEXT("force_malformed_result"))){FFileHelper::SaveStringToFile(TEXT("{malformed"),*OP);Append(R,TEXT("N2C_TEST_FAULT_INJECTION|type=malformed_child_result"));return true;}if(!WriteJsonAtomic(OP,O,E)){Append(R,TEXT("N2C_FRESH_VERIFY_RESULT_V3|result=FAIL|code=result_write_failed"));return true;}Append(R,FString::Printf(TEXT("N2C_FRESH_VERIFY_RESULT_V3|verification_result=%s|process_execution=PASS|code=%s"),Pass?TEXT("PASS"):TEXT("FAIL"),*Code));return true;
}
